name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - THET-92-Deploy-Branch  # You can change this to any branch you want

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      # Step 3: Echo test message to ensure SSH connection works
      - name: Test SSH Connection
        run: |
          ssh -i ~/.ssh/id_rsa root@${{ secrets.SERVER_HOST }} "echo 'SSH connection successful!'"

      # Step 4: SSH into server and run the script that is already on the server
      - name: SSH into server and run the script
        run: |
          ssh -i ~/.ssh/id_rsa root@${{ secrets.SERVER_HOST }} "bash ~/app/current_deploy/current_app/TrafficHelper/merge.sh"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
